services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
  miflora-mqtt-daemon:
    image: ghcr.io/ssolimany/miflora-mqtt-daemon:latest
    container_name: miflora-mqtt-daemon
    environment:
      MQTT_HOSTNAME: localhost
      MQTT_PORT: 1883
      MQTT_USERNAME: user
      MQTT_PASSWORD: pwd123
    volumes:
      - ./mqtt/sensors:/config
    network_mode: host
  eclipse-mosquitto:
    image: eclipse-mosquitto:2
    container_name: eclipse-mosquitto
    ports:
      - 1883:1883
    user: "1883"
    volumes:
      - ./mqtt/server/config:/mosquitto/config:rw

secrets:
  influxdb2-admin-username:
    file: influxdb/.influxdb2-admin-username
  influxdb2-admin-password:
    file: influxdb/.influxdb2-admin-password
  influxdb2-admin-token:
    file: influxdb/.influxdb2-admin-token
volumes:
  influxdb2-data:
  influxdb2-config:
